name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.5
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http:
  meta:
  json_annotation:

dev_dependencies:
  test:
  pedantic:
  build_runner:
  json_serializable:
  coverage:
